from random import randint,shuffle;from _2048 import GameOver,COLOURS,rgb,product,EmptyCell
class BaseCell(EmptyCell):__format__=lambda s,f='0':'\x1b[90m'+7*' _'[f=='2'and s.coords[1]+s.coords[3]==6]
class Cell(BaseCell):__init__=lambda s,w,x,y,z,v=0:setattr(s.move(w,x,y,z),'value',v or 2*randint(1,2));__bool__=lambda s:1>0;is_empty=0>0;__eq__=lambda s,o:not[*{int(s),int(o)}][1:];__hash__=lambda s:int(s);colour=lambda s,T:(lambda r,g,b,t:rgb(r,g,b,1,1)(rgb(t,t,t)(T)))(*COLOURS[int(s)]);__str__=lambda s:f"{int(s): ^21d}";__format__=lambda s,f='1':s.colour(str(s)[int(f)*7:7+int(f)*7].__format__(f' {"<^>"[int(f)]}7s').replace(' ',[' ','\x1b[90m_'][f=='2'and s.coords[1]+s.coords[3]==6]))
class Engine:
  def __init__(self):self.matrix=[[[[BaseCell(i,j,k,l)for i in range(4)]for j in range(4)]for k in range(4)]for l in range(4)];r=lambda a:shuffle(a)or a[:16];a=[Cell(*c,2)for c in r([*self])];[()for x in a for self[x]in[x]]
  def empty(self,*c):x=self[c]=BaseCell(*c);return x
  def swipe(self,d):
    def s(i,j,k,r):m=[self[((i,q,j,k),(q,i,j,k),(i,j,k,q),(i,j,q,k))[d//2]]for q in r][::1-2*(d in(1,2,5,6))];q=[*filter(bool,map(int,m))];q+=[0]*(4-len(q));[q.__setitem__(l,[2*q.pop(l+1),q.append(0)][0])for l in range(3)if q[l]and q[l]==q[l+1]];[self.__setitem__(m[l],n)for l,n in enumerate(q)];return q!=[*map(int,m)]
    r=*range(4),;(r:=any([s(*i,r)for i in product(r,r,r)]))and((_:=[*filter(lambda x:not self[x],self)]),shuffle(_),(_:=_[:16]),[self.__setitem__(a,Cell(*a))for a in _]),self.gameend and(()for()in()).throw(GameOver(['Game lost', 'Game won'][self.gamewon]));return["swiped "+['up','down','right','left','in','out','forward','backward'][d],"Game Won","invalid move"][max(2*(not r),self.gamewon)].__format__(' <18s')
  gameend=property(lambda self:all([self[a]for a in self])and not[0 for a in self for _ in[1,-1]for offset in[(_,0,0,0),(0,_,0,0),(0,0,_,0),(0,0,0,_)]for b in[(*[x+y for x,y in zip(a,offset)],)]if len([*filter(range(4).__contains__,b)])==4 if self[a]==self[b]]);up,down,right,left,in_,out,forward,backward=[(lambda s,j=i:s.swipe(j)+'\n'+str(s))for i in range(8)];set=lambda s,i,j,k,l,n:s.__setitem__((i,j,k,l),[Cell,BaseCell][not n](i,j,k,l,*(n,)*bool(n)))or s;__iter__=lambda s:iter(product(range(4),repeat=4));gamewon=property(lambda s:any([int(s[a])>=2<<30 for a in s]));__bool__=lambda s:not s.gameend;__setitem__=lambda self,item,value:(lambda i,j,k,l:self.matrix[l][k][j].__setitem__(i,[Cell,BaseCell][not value](*item,*[[value],()][not value])if type(value)==int else value))(*item);__str__=__repr__=lambda self:'[\n '+',\n '.join(['[\n  '+',\n  '.join(map(lambda a:str([str(list(map(int,e))).__format__(' <25s')for e in a]),self.matrix[k]))+'\n ]' for k in range(4)]).replace("'",'')+'\n]';__getitem__=lambda self,item:(lambda i,j,k,l:self.matrix[l][k][j][i])(*item);load=lambda self,m:[self[w,x,y,z]for w,x,y,z in self for self[w,x,y,z]in[m[z][y][x][w]]];__bool__=lambda s:1>0
class Interface:
  input=__import__('msvcrt')if __import__('os').name=='nt'else type('msvcrt',(),{'getch':lambda:'\x1b','kbhit':lambda:True});os=__import__('os');__getitem__=lambda s,i:s.eng[i];__setitem__=lambda s,i,v:s.eng.__setitem__(i,v)
  def __init__(self,engine=None):
    try:input("resize window");self.install(engine or Engine());self.run()
    except GameOver as e:self.next_frame('Game Over');print(f'\x1b[H\x1b[2K{str(e): <20}'+'\n'*76)
    except Exception as e:raise type('YouFuckedUp',(Exception,),{'__name__':'YouFuckedUp','__qualname__':'YouFuckedUp'})from e
  def quit(self):raise GameOver(["Game quit","Game won"][self.eng.gamewon])
  def uninstall(self):eng=self.eng;del self.eng;return eng
  def install(self,engine):self.eng=engine
  def next_frame(s,message=''):r=lambda:range(4);print(f"""\x1b[H\x1b[0m{message}\x1b[90m^{"|^=|^".join(['|^~|^'.join(['|^'.join(['@@'.join(['|'.join([f"{s.eng[i,j,k,l]:{m}}"for i in r()])for k in r()])for m in map(str,range(3))])for j in r()])for l in r()])}/\x1b[m\x1b[A""".replace('~','@@'.join(['+'.join(4*['-'*7])]*4)).replace('=','@'*130).replace('@','\x1b[100m \x1b[49m').replace('^','\n\x1b[90m').replace('|','\x1b[90m|'))
  def run(self):
    self.eng and print('\x1b[H',end='\x1bc');self.next_frame("Game Start.")
    while not self.eng.gameend:(c:=self.input.kbhit()and self.input.getch().decode('ANSI')or'')and self.next_frame({c in'wasd':lambda:self.eng.swipe(str.maketrans('wasd','\0\3\1\2')[ord(c)]),c=='\xe0':lambda:(lambda _c:self.eng.swipe(str.maketrans('KHMP','\7\4\6\5')[_c])if chr(_c)in'KHMP'else self.quit())(ord(self.input.getch().decode('ANSI'))),c=='\x1b':self.quit}.get(1>0,lambda:'')())
game_won=__name__=='__main__'and Interface().eng.gamewon